name: derasika2
description: IIDX score csv manager.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^3.2.0
  cupertino_icons: ^1.0.2
  file_picker: ^4.2.0
  flutter_hooks: ^0.18.0
  freezed_annotation: ^1.0.0
  hooks_riverpod: ^1.0.0
  json_serializable: ^6.1.1
  path_provider: ^2.0.6
  share_plus: ^3.0.4
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.12
  json_annotation: ^4.4.0
  intl: ^0.17.0
  webview_flutter: ^3.0.0
  fl_chart: ^0.40.2
  collection: ^1.15.0
  flutter_sticky_header: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.0.1
  freezed:
  build_runner:

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
